/*
* Copyright (c) 2002-2004 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/


// This header file contains the customisation implementation identity for Adaptation_Layer_AppLayout_Elaf
// It was generated by hand, not by layout compiler.
// This file may be manually modified.

#ifndef ADAPTATION_LAYER_APPLAYOUT_ELAF_H
#define ADAPTATION_LAYER_APPLAYOUT_ELAF_H
#include "AppLayout.cdl.custom.h"
#include "Adaptation_Layer_AppLayout_Elaf.hrh"

namespace Adaptation_Layer_AppLayout_Elaf
{

const TInt KCdlInstanceId = _CDL_Adaptation_Layer_AppLayout_Elaf_KCdlInstanceId;
using AppLayout::KCdlInterface;
using AppLayout::KCdlInterfaceUidValue;
GLREF_D const AppLayout::SCdlImpl KCdlImpl;

} // end of namespace Adaptation_Layer_AppLayout_Elaf
#endif // ADAPTATION_LAYER_APPLAYOUT_ELAF_H
