/*
* Copyright (c) 2002-2004 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/


// This header file contains the customisation implementation identity for Adaptation_Layer_AknApacLayout
// It was generated by hand, not by layout compiler.
// This file may be manually modified.

#ifndef ADAPTATION_LAYER_AKNAPACLAYOUT_H
#define ADAPTATION_LAYER_AKNAPACLAYOUT_H
#include "AknApacLayout.cdl.custom.h"
#include "Adaptation_Layer_AknApacLayout.hrh"

namespace Adaptation_Layer_AknApacLayout
{

const TInt KCdlInstanceId = _CDL_Adaptation_Layer_AknApacLayout_KCdlInstanceId;
using AknApacLayout::KCdlInterface;
using AknApacLayout::KCdlInterfaceUidValue;
GLREF_D const AknApacLayout::SCdlImpl KCdlImpl;

} // end of namespace Adaptation_Layer_AknApacLayout
#endif // ADAPTATION_LAYER_AKNAPACLAYOUT_H
