/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for Adaptation_Layer_AknLayout_Elaf
// It was generated by hand, not by layout compiler.
// This file may be manually modified.

#ifndef ADAPTATION_LAYER_AKNLAYOUT_ELAF_H
#define ADAPTATION_LAYER_AKNLAYOUT_ELAF_H
#include "AknLayout.cdl.custom.h"
#include "Adaptation_Layer_AknLayout_Elaf.hrh"

namespace Adaptation_Layer_AknLayout_Elaf
{

const TInt KCdlInstanceId = _CDL_Adaptation_Layer_AknLayout_Elaf_KCdlInstanceId;
using AknLayout::KCdlInterface;
using AknLayout::KCdlInterfaceUidValue;
GLREF_D const AknLayout::SCdlImpl KCdlImpl;

} // end of namespace Adaptation_Layer_AknLayout_Elaf

#endif // ADAPTATION_LAYER_AKNLAYOUT_ELAF_H
