/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for LayoutMetaData_touchpane
// It was generated by:
// cdlcompiler instance ..\cdl\LayoutMetaData.cdl LayoutMetaData_touchpane
// This file may be manually modified.

#ifndef LAYOUTMETADATA_TOUCHPANE_H
#define LAYOUTMETADATA_TOUCHPANE_H
#include "layoutmetadata.cdl.custom.h"
#include "layoutmetadata_touchpane.hrh"

namespace LayoutMetaData_touchpane
{

const TInt KCdlInstanceId = _CDL_LayoutMetaData_touchpane_KCdlInstanceId;
using Layout_Meta_Data::KCdlInterface;
using Layout_Meta_Data::KCdlInterfaceUidValue;
GLREF_D const Layout_Meta_Data::SCdlImpl KCdlImpl;

} // end of namespace LayoutMetaData_touchpane
#endif // LAYOUTMETADATA_TOUCHPANE_H
