/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for CdlFontInst_vga_touch
// It was generated by:
// cdlcompiler instance \S60\mw\uiresources\layouts\aknlayout2\cdl\CdlFont.cdl CdlFontInst_vga_touch
// This file may be manually modified.

#ifndef CDLFONTINST_VGA_TOUCH_H
#define CDLFONTINST_VGA_TOUCH_H
#include "cdlfont.cdl.custom.h"
#include "cdlfontinst_vga_touch.hrh"

namespace CdlFontInst_vga_touch
{

const TInt KCdlInstanceId = _CDL_CdlFontInst_vga_touch_KCdlInstanceId;
using CDL_Font::KCdlInterface;
using CDL_Font::KCdlInterfaceUidValue;
GLREF_D const CDL_Font::SCdlImpl KCdlImpl;

} // end of namespace CdlFontInst_vga_touch
#endif // CDLFONTINST_VGA_TOUCH_H
