/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for CdlFontInst_qhd_touch
// It was generated by:
// cdlcompiler instance \S60\mw\uiresources\layouts\aknlayout2\cdl\CdlFont.cdl CdlFontInst_qhd_touch
// This file may be manually modified.

#ifndef CDLFONTINST_QHD_TOUCH_H
#define CDLFONTINST_QHD_TOUCH_H
#include "CdlFont.cdl.custom.h"
#include "cdlfontinst_qhd_touch.hrh"

namespace CdlFontInst_qhd_touch
{

const TInt KCdlInstanceId = _CDL_CdlFontInst_qhd_touch_KCdlInstanceId;
using CDL_Font::KCdlInterface;
using CDL_Font::KCdlInterfaceUidValue;
GLREF_D const CDL_Font::SCdlImpl KCdlImpl;

} // end of namespace CdlFontInst_qhd_touch
#endif // CDLFONTINST_QHD_TOUCH_H
