/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for CdlFontInst_double
// It was generated by:
// cdlcompiler instance ..\cdl\CdlFont.cdl CdlFontInst_double
// This file may be manually modified.

#ifndef CDLFONTINST_DOUBLE_H
#define CDLFONTINST_DOUBLE_H
#include "CdlFont.cdl.custom.h"
#include "CdlFontInst_double.hrh"

namespace CdlFontInst_double
{

const TInt KCdlInstanceId = _CDL_CdlFontInst_double_KCdlInstanceId;
using CDL_Font::KCdlInterface;
using CDL_Font::KCdlInterfaceUidValue;
GLREF_D const CDL_Font::SCdlImpl KCdlImpl;

} // end of namespace CdlFontInst_double
#endif // CDLFONTINST_DOUBLE_H
