/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// displaylayoutmetricsinst_qvga_touch generated by
// cdlcompiler instance -p..\displaylayoutmetrics ..\cdl\displaylayoutmetrics.cdl displaylayoutmetricsinst_qvga_touch
// This customisation implements the interface defined in displaylayoutmetrics.cdl

#include "displaylayoutmetricsinst_qvga_touch.h"

namespace displaylayoutmetricsinst_Qvga_touch
{

TReal32 UnitValue()
	{
	return 5.3f;
	}


const Display_Layout_Metrics::SCdlImpl KCdlImpl = 
	{
	&UnitValue,
	};

} // end of namespace displaylayoutmetricsinst_qvga_touch
