/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/

// This header file contains the customisation implementation identity for displaylayoutmetricsinst_Nhd4
// It was generated by:
// cdlcompiler instance -p..\displaylayoutmetrics ..\cdl\displaylayoutmetrics.cdl displaylayoutmetricsinst_Nhd4
// This file may be manually modified.

#ifndef DISPLAYLAYOUTMETRICSINST_NHD4_H
#define DISPLAYLAYOUTMETRICSINST_NHD4_H
#include "displaylayoutmetrics.cdl.custom.h"
#include "displaylayoutmetricsinst_nhd4.hrh"

namespace displaylayoutmetricsinst_Nhd4
{

const TInt KCdlInstanceId = _CDL_displaylayoutmetricsinst_Nhd4_KCdlInstanceId;
using Display_Layout_Metrics::KCdlInterface;
using Display_Layout_Metrics::KCdlInterfaceUidValue;
GLREF_D const Display_Layout_Metrics::SCdlImpl KCdlImpl;

} // end of namespace displaylayoutmetricsinst_Nhd4
#endif // DISPLAYLAYOUTMETRICSINST_NHD4_H
