/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/
// This header file contains the customisation implementation identity for series60skinIndexDll_inst
// It was generated by:
// MifToCdlIndex -p..\..\srcdata\scalableseries60skin\MifIndexDll series60skin.mif series60skinIndexDll 0x101f84b9
// This file may be manually modified.

#ifndef SERIES60SKININDEXDLL_INST_H
#define SERIES60SKININDEXDLL_INST_H
#include "mifheader.cdl.custom.h"
#include "series60skinindexdll_inst.hrh"

namespace series60skinIndexDll_inst
{

const TInt KCdlInstanceId = _CDL_series60skinIndexDll_inst_KCdlInstanceId;
using MifHeader::KCdlInterface;
using MifHeader::KCdlInterfaceUidValue;
GLREF_D const MifHeader::SCdlImpl KCdlImpl;

} // end of namespace series60skinIndexDll_inst
#endif // SERIES60SKININDEXDLL_INST_H
